### ISSUE TITLE
Getting error: "Unable to create API" when trying to make API endpoints

### ISSUE THREAD

**Issue by zachschultz** [IBM-Bluemix/openwhisk-workshops#5]
At this section in the bootcamp:

```
Next, let's map API endpoints to actions:

$ wsk api create /books GET endpoint_get
ok: created API /books GET for action /_/endpoint_get
https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/8326f1d8a3dbc5afd14413a2682b7a78e17a55ee352f6c03f6be82718d69726e/books

$ wsk api create /books POST endpoint_post
ok: created API /books POST for action /_/endpoint_post
https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/8326f1d8a3dbc5afd14413a2682b7a78e17a55ee352f6c03f6be82718d69726e/books

$ wsk api create /books DELETE endpoint_delete
ok: created API /books DELETE for action /_/endpoint_delete
https://service.us.apiconnect.ibmcloud.com/gws/apigateway/api/8326f1d8a3dbc5afd14413a2682b7a78e17a55ee352f6c03f6be82718d69726e/books
```

upon running the commands I get this error message: `error: Unable to create API: API creation failure: Unable to obtain API(s) from the API Gateway (status code 400): {"error":{"statusCode":400,"message":"User access token is required"}}`

When I try to run `wsk bluemix login --sso` to see if it would solve the issue, I then get the error: `error: Unable to retrieve namespaces: accessToken token seems to be invalid. (code 61789)`

I do have my wsk auth set up, and `wsk property get --auth` does return my correct auth token from OpenWhisk on the Bluemix console

**Comment by andreasnauerz** [comment]
Cannot reproduce this; maybe this was a temp issue?
